
#Client tweaks
[client]
	#If Powder Snow should drop snow particles if there is no block below.
	"Powder Snow Particles" = true
	#Displays "Dyeable" tooltip under dyeable items.
	"Dyeable Tooltip" = false

